{% set name = "cellfinder-napari" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellfinder-napari-{{ version }}.tar.gz
  sha256: c5e3665eb87ffdc5abec99fdc9cbd493752c5f29689b5e9d2b6ea83b65ee1aed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - brainglobe-napari-io
    - cellfinder-core >=0.3
    - imlib
    - magicgui
    - napari
    - napari-ndtiffs
    - napari-plugin-engine >=0.1.4
    - numpy
    - pooch >=1
    - python >=3.7
    - qtpy
    - scikit-image
    - tifffile

test:
  imports:
    - cellfinder_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - oclgrind

about:
  home: https://brainglobe.info/cellfinder
  summary: Efficient cell detection in large images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
