{% set name = "cellfinder-napari" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellfinder-napari-{{ version }}.tar.gz
  sha256: e89b8e45e23e1108d8c58a019a641c47451ba632b65b5e45df4dfae32ba52ad2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - brainglobe-napari-io
    - cellfinder-core >=0.2.4
    - napari
    - napari-ndtiffs
    - napari-plugin-engine >=0.1.4
    - python >=3.7

test:
  imports:
    - cellfinder_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - oclgrind

about:
  home: https://brainglobe.info/cellfinder
  summary: Efficient cell detection in large images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - adamltyson
