{% set name = "cellfinder-napari" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cellfinder-napari-{{ version }}.tar.gz
  sha256: e87cb277520a35e60edfe692b908a48666f390136777ef9b482fcc6e604595e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - brainglobe-napari-io
    - cellfinder-core >=0.3
    - imlib
    - magicgui
    - napari
    - napari-ndtiffs
    - napari-plugin-engine >=0.1.4
    - numpy
    - pooch >=1
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - tifffile

test:
  imports:
    - cellfinder_napari
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - oclgrind
    - python {{ python_min }}

about:
  home: https://brainglobe.info/cellfinder
  summary: Efficient cell detection in large images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder-napari

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
